(feat/#4): 공통 컴포넌트 SpotButton, CategoryField 생성
guhwangjakmul/ending-to-change pull request #10
Opened 2024-10-31 18:06 UTC by ryukyung

### 🖼️ Screen shot

| 완성 이미지/GIF |
| :-------------: |
| <img src='https://github.com/user-attachments/assets/8ee31909-b3fc-4eda-9034-351663150eee' />  |

https://github.com/user-attachments/assets/b8b6b726-5043-4577-99db-52bf10871f46

### ✅ 작업 내용
- 공통 컴포넌트 `SpotButton`, `CategoryField` 생성

### 📝 Details

- `SpotButton`
  - 필수 `props`
    - `name` : 카테고리명 (air, energy, recycle, soil, warming, water)
    - `status` : 버튼의 상태 (default, selected, completed)
    - `onClick` : 버튼 클릭 시 동작할 이벤트 함수
- `CategoryField`
  - 옵셔널 `props`
    - `isClickable` : 클릭할 수 있는 환경이면 `true`, 클릭할 수 없는 환경이면 `false`(default: `true`)

### 💻 예시코드

```jsx
{/* 클릭할 수 있는 환경 ex. 카테고리 선택 페이지 */}
<CategoryField />
{/* 클릭할 수 없는 환경 ex. 마이페이지 */}
<CategoryField isClickable={false} />
```

### ⚠️ 주의사항
- 아직 데이터가 없기 때문에 대략적인 데이터를 넣었습니다. 추후에 데이터 처리 할 예정입니다.

2024-10-31 19:57 UTC, HalamLee requested changes
현재 영상을 보면 completed 상태에서도 클릭이 가능한 것처럼 보이는데, 이는 SpotButton 컴포넌트에서 isClickable prop이 false 또는 true일 때 처리할 내용이 빠져서 그런 것 같습니다.
확인 바랍니다~

2024-10-31 19:57 UTC, HalamLee commented on src/components/common/CategoryField.tsx
> +          isClickable={isClickable}
`SpotButton` 컴포넌트 코드에 `isClickable`을 넘기면 어떻게 동작하는지 구현부가 빠져있는 것 같습니다..

2024-10-31 19:57 UTC, HalamLee commented on src/components/common/SpotButton.tsx
> +  const { name, status, onClick } = props
아마 여기 props에서 `isClickable`을 구조분해할당하지 않아서 잊은 것 같은데.. 이 경우 디폴트값으로 false를 주면 해결 될 것 같아요
```suggestion
  const { name, status, onClick, isClickable = false } = props
```

2024-10-31 19:57 UTC, HalamLee commented on src/components/common/SpotButton.tsx
> +  const { name, status, onClick } = props
구현부 작성 부탁드리겠습니당

2024-11-01 05:16 UTC, ujeans commented
확인

2024-11-01 06:12 UTC, ji1210h commented
확인했습니다

2024-11-01 06:12 UTC, merged

2024-11-01 06:13 UTC, HalamLee commented
ㅜㅜㅜㅜㅜㅜㅜㅜㅜㅜㅜㅜㅜㅜㅜㅜㅜ 이거 머지하면 안 됐는데

2024-11-01 15:15 UTC, ryukyung commented
댓글에서 이야기한 것들 처리하구 이 브랜치로 다시 PR보내겠슴미당